name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'

      - name: Restore NuGet packages
        run: nuget restore hook_lib.sln

      - name: Build solution
        run: msbuild hook_lib.sln /p:Configuration=Release

      - name: Archive DLL
        uses: actions/upload-artifact@v3
        with:
          name: dll
          path: path/to/your/output/Directory/YourDll.dll

